# Generated by Django 4.1.7 on 2023-03-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('author', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterID', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webDB.book')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicID', models.CharField(blank=True, default='', max_length=100)),
                ('topicName', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentenceText', models.CharField(blank=True, default='', max_length=1000)),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webDB.book')),
                ('topicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webDB.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Character2Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webDB.character')),
                ('sentenceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webDB.sentence')),
            ],
        ),
    ]
