# Generated by Django 4.1.7 on 2023-03-05 10:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.CharField(blank=True, default='', max_length=100)),
                ('bookName', models.CharField(blank=True, default='', max_length=500)),
                ('bookauthor', models.CharField(blank=True, default='', max_length=500)),
                ('bookAuthorYearOfBirth', models.CharField(blank=True, default='', max_length=50)),
                ('bookAuthorYearOfDeath', models.CharField(blank=True, default='', max_length=50)),
                ('bookLanguage', models.CharField(blank=True, default='', max_length=500)),
                ('bookSubjects', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=100)),
                ('bookID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webDB.book')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicID', models.IntegerField(default=0)),
                ('TopicName', models.CharField(blank=True, default='', max_length=100)),
                ('Top_n_words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=15)),
                ('bookID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webDB.book')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentenceText', models.TextField(default='')),
                ('sentIDBook', models.IntegerField(default=0)),
                ('bookID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webDB.book')),
                ('topicID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webDB.topic')),
            ],
        ),
        migrations.CreateModel(
            name='sent2char',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webDB.character')),
                ('sentID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webDB.sentence')),
            ],
        ),
    ]
