# Generated by Django 4.1.7 on 2023-03-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookAuthorYearOfBirth',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookAuthorYearOfDeath',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookLanguage',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookName',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookSubjects',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookauthor',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
