# Generated by Django 4.1.7 on 2023-03-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookID',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
