# Generated by Django 4.1.7 on 2023-03-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webDB', '0002_alter_book_bookid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='bookAuthor',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='bookName',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='topicID',
        ),
        migrations.AddField(
            model_name='sentence',
            name='sentenceIndex',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Character2Sentence',
        ),
    ]
