# Generated by Django 4.1.7 on 2023-03-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webDB', '0002_alter_book_bookauthoryearofbirth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='bookIndex',
            new_name='bookID',
        ),
        migrations.AlterField(
            model_name='sentence',
            name='sentenceIDBook',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topicID',
            field=models.IntegerField(default=0),
        ),
    ]
