# Generated by Django 4.1.7 on 2023-03-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webDB', '0003_rename_author_book_bookauthor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookAuthor',
            new_name='bookauthor',
        ),
    ]
