# Generated by Django 4.1.7 on 2023-03-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webDB', '0003_rename_bookindex_topic_bookid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='sentenceIDBook',
            new_name='sentIDBook',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topicID',
            new_name='TopicID',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topicName',
            new_name='TopicName',
        ),
    ]
