# Generated by Django 4.1.7 on 2023-03-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webDB', '0004_rename_sentenceidbook_sentence_sentidbook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='Name',
        ),
    ]
