# Generated by Django 4.1.7 on 2023-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webDB', '0005_rename_name_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentenceText',
            field=models.TextField(default=''),
        ),
    ]
